---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 20.6.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    namespaceOverride: ""
    image:
      registry: docker.io
      repository: bitnami/redis
      tag: 7.4.2-debian-12-r0
    ## @param architecture Redis&reg; architecture. Allowed values: `standalone` or `replication`
    architecture: replication
    ## ref: https://github.com/bitnami/containers/tree/main/bitnami/redis#setting-the-server-password-on-first-run
    auth:
      usePassword: false
      # usePasswordFiles: true
      # existingSecret: redis-password-secret
      # existingSecretPasswordKey: dis-password.yaml
    commonConfiguration: |-
      # Enable AOF https://redis.io/topics/persistence#append-only-file
      appendonly yes
      # Disable RDB persistence, AOF persistence already enabled.
      save ""
    existingConfigmap: ""
    master:
      revisionHistoryLimit: 10
      ## ref: https://redis.io/topics/config
      configuration: ""
      containerPorts:
        redis: 6379
      livenessProbe:
        enabled: true
        initialDelaySeconds: 20
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      readinessProbe:
        enabled: true
        initialDelaySeconds: 20
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 5
      resourcesPreset: "micro"
      resources: {}
      kind: StatefulSet
      updateStrategy:
        type: RollingUpdate
      ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
      persistence:
        size: 8Gi
      service:
        type: ClusterIP
        portNames:
          redis: "tcp-redis"
        ports:
          redis: 6379
      terminationGracePeriodSeconds: 30
    replica:
      kind: StatefulSet
      replicaCount: 3
      revisionHistoryLimit: 10
      configuration: ""
      disableCommands:
        - FLUSHDB
        - FLUSHALL
      containerPorts:
        redis: 6379
      startupProbe:
        enabled: true
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 22
      livenessProbe:
        enabled: true
        initialDelaySeconds: 20
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      readinessProbe:
        enabled: true
        initialDelaySeconds: 20
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 5
      resourcesPreset: "micro"
      resources: {}
      updateStrategy:
        type: RollingUpdate
      minReadySeconds: 0
      persistence:
        size: 8Gi
      service:
        type: ClusterIP
        ports:
          redis: 6379
        externalTrafficPolicy: Cluster
        internalTrafficPolicy: Cluster
        clusterIP: ""
        loadBalancerIP: ""
      terminationGracePeriodSeconds: 30
