# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    labels:
        app.kubernetes.io/name: redis
type: Opaque
stringData:
    redis_password: ENC[AES256_GCM,data:NymPOc15DK2LylRqfCvsiWuyhaG3uKLO,iv:WSni7UdaGsTMGvShXRHanym8TDU98KUjvOZllsHdlKk=,tag:hUsa8IxxFj0lGiTftnk70A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ2dZRHhHaGdLM2c4UUNT
            dHQ0UGdSb3NFUGxxMlUxTE1jVFNSMFA0TjJnCnlUdXdLSm54YkdITk1uNER0aGxW
            T2ZIdXd5MFhXNXBKajl4VlNraUVwb2sKLS0tIDc3T1JmQTczbkF6eGxLS2NjNW9C
            Sm91TjBvSEl6ZmNoV09WaUJGNlBlQTgKXi1MXW6WPh8Vk2DpcmhVqS6TavZ906Hn
            Z8ilaBvClXcd32HnF2qR0Ys8aMbZH3uI2Mdf2OOBo47FoO5p4Q2o+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T09:08:18Z"
    mac: ENC[AES256_GCM,data:MR3sztk69t8vIAhFWS1EZHsAZ4/b7aDUWYwbRIVUCsQwsQQ7ou1rI6drR5QnMZxQ1teyuw73BPPxu97ZYkygZK2rUZsrqhlx5AAkMxPmVH1qpLkxdXQE/LQkTmfG1D9+uWQHH5nQ6xQsqkgk+Bw2XRwvUYr2VuVH58vAYnrgLRo=,iv:BJNs5XFZWN4nMX9EFstgvCVvH/lL1JwXYPQp5WYUs4o=,tag:4Lz5nxd4+2Fwj03Q2ZyFYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.9.2
