# apps/production/home-assistant/deployment-patch.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  template:
    spec:
      containers:
        - name: ha-ssh-access
          image: openssh-server
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Europe/Amsterdam"
          - name: USER_NAME
            value: "{{shell_user}}"
          - name: USER_PASSWORD
            value: "{{shell_password}}"
          - name: PASSWORD_ACCESS
            value: "false"
          - name: SUDO_ACCESS
            value: "true"
          - name: PUBLIC_KEY_URL
            value: "${PUBLIC_KEY_URL}"
        - name: homeassistant
          image: home-assistant
          env:
            - name: TZ
              value: Europe/Amsterdam
