# apps/production/home-assistant/kustomization.yaml
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
- ../../base/home-assistant
- namespace.yaml
patches:
  - path: pvc-patch.yaml
    target:
      kind: PersistentVolumeClaim
  - path: ingressroute-patch.yaml
    target:
      kind: IngressRoute
images:
- name: debian
  newName: $HARBOR_REGISTRY}/debian
  newTag: 12.6-slim
- name: openssh-server
  newTag: "1.0"
  newName: ${HARBOR_REGISTRY}/openssh-server
- name: home-assistant
  newTag: "2024.9"
  newName: ${HARBOR_REGISTRY}/home-assistant