# apps/production/home-assistant/pvc-patch.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassistant-data
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
