# apps/production/home-assistant/ssh-configmap.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: homeassistant-conf
stringData:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Amsterdam"
  USER_NAME: beheerder
  USER_PASSWORD: 'F!esG33ST'
  PASSWORD_ACCESS: "false"
  SUDO_ACCESS: "true"
  PUBLIC_KEY_URL: https://github.com/crazyelectron-io.keys
