# apps/base/part-db/pg-secrets-patch.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: partdb-cnpg-user-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Lnta0CtPaFXUGNE=,iv:XI1Bg229/N6uSaPCMovCIl2lQTaM056LMPqMyP7VNU0=,tag:Y0VV2yMLzCWiERlD1f7V+w==,type:str]
    password: ENC[AES256_GCM,data:O1pfCVUkEpS+VlxBU0NiBlg=,iv:DIicrAVgJzkvFQFd5n6bsGiTIkHYrC9Wenrp4d2VCUo=,tag:1teQ0UCB+H5+kmMOu0vodA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKT3Q4K0ZhUVdVRnFVOURY
            elpVN3JkdzM4aWhaUDc2THd6bjJ1ZEtaUm40CkJ2dzRvT2hRQml3dHVhSnNJajFO
            UE4ySWIxU216UDkwN0x3UVhEc0wwR2MKLS0tIHdKbW14OWtzaHZVcGhRelZBUzFk
            ZE1OZFZ4RDF5MWRvQkVsR0tCWG00enMKCZ9Tb3QQUt8CdduDensezovXpAqMr/eg
            eh8KVNCVCyq4/BFYMbIQtlLtXzJMw9Jfyp/cLbspsZUIc5sCdeu3pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-05T15:36:44Z"
    mac: ENC[AES256_GCM,data:YE3XlmCEpTXnaqSkCYyyqZqgSHxh1yQpHUbKPJCwvVKNqMiRpWL9caZeFm2uUtyUfTM6m9pqFv0IfgcyOQnAURBWdIYhL4af8J+t33pvX3RQV4ViGwIOWtTYjMbmhgxpl3j86KLaBTm3PpbS9ZO1mmOm+2wBoJv5ZaFCd4TdAHo=,iv:pbmA/wjsQcWsrrfcVslq8v4k9DrawNJ0XXGly4LTUq8=,tag:6QgOIWFJLj6zT0yWH1u5lQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
