[paths]
data = /var/lib/grafana/
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[analytics]
enabled = true
reporting_enabled = false
check_for_updates = true
check_for_plugin_updates = true
feedback_links_enabled = false
[security]
;;disable_initial_admin_creation = false
admin_user = ${SECRET_GRAFANA_ADMIN_USER}
admin_password = ${SECRET_GRAFANA_ADMIN_PASSWORD}
admin_email = ${SECRET_EMAIL_1}
disable_brute_force_login_protection = false
allow_embedding = true
[live]
# Set to 0 to disable Grafana Live websocket connections
max_connections = 0
[log]
mode = console
;Either "debug", "info", "warn", "error", "critical", default is "info"
level = info
[grafana_net]
url = https://grafana.net
[server]
protocol = http
http_addr = 0.0.0.0
http_port = 3000
domain = grafana.${SECRET_DOMAIN_0}
root_url = https://grafana.${SECRET_DOMAIN_0}
enforce_domain = false
serve_from_sub_path = true
router_logging = true
enable_gzip = true
[date_formats]
default_week_stat = monday
default_time_zone = Europe/Amsterdam
[metrics]
enabled = true
[database]
type = postgres
host = grafana-cluster-rw.monitoring-system.svc.cluster.local
name = grafana_db
user = ${SECRET_GRAFANA_PG_USER}
password = ${SECRET_GRAFANA_PG_PASSWORD}
query_retries = 1
[auth]
signout_redirect_url = https://auth.${SECRET_DOMAIN_0}/application/o/grafana/end-session/
oauth_auto_login = true
[auth.generic_oauth]
name = authentik
enabled = true
auto_login = true
allow_sign_up = false
allow_assign_grafana_admin = true
client_id = ${SECRET_GRAFANA_OAUTH_CLIENT_ID}
client_secret = ${SECRET_GRAFANA_OAUTH_CLIENT_SECRET}
scopes = openid email profile offline_access groups
auth_url = https://auth.${SECRET_DOMAIN_0}/application/o/authorize/
token_url = https://auth.${SECRET_DOMAIN_0}/application/o/token/
api_url = https://auth.${SECRET_DOMAIN_0}/application/o/userinfo/
; role_attribute_path = groups[?contains(@, 'GrafanaAdmins') == true] && 'Admin' || groups[?contains(@, 'GrafanaEditors') == true] && 'Editor' || 'Viewer'
role_attribute_path = contains(groups[*], 'GrafanaAdmin') && 'Admin' || contains(groups[*], 'GrafanaEditor') && 'Editor' || 'Viewer'
; role_attribute_path = containes(groups, 'GrafanaAdmins') && 'Admin' || contains(groups, 'GrafanaEditors') && 'Editor' || 'Viewer'
[auth.anonymous]
enabled = false
# Organization name that should be used for unauthenticated users
org_name = Main Org.
org_role = Viewer
