# infrastructure/base/reloader/kustomization.yaml
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml
  - deployment.yaml