# infrastructure/base/reloader/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml
  - deployment.yaml