# clusters/production/cluster-monitoring.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-monitoring
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/crazyelectron-io/cluster-monitoring
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-monitoring
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  prune: true
  path: ./kustomize/production
  sourceRef:
    kind: GitRepository
    name: cluster-monitoring
