apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-service-monitor
  labels:
    app.kubernetes.io/name: source-controller
spec:
  endpoints:
    - port: source-controller-metrics
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchLabels:
      name: source-controller
      release: prometheus