---
apiVersion: v1
kind: Service
metadata:
  name: flux-metrics
  labels:
    # app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: flux-metrics
    release: prometheus
spec:
  type: ClusterIP
  ports:
    - name: flux-metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    # app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: source-controller