---
apiVersion: v1
kind: Service
metadata:
  name: source-controller-metrics
  labels:
    app.kubernetes.io/instance: source-controller
    app.kubernetes.io/name: source-controller-metrics
    release: prometheus
spec:
  type: ClusterIP
  ports:
    - name: source-controller-metrics
      port: 8080
      targetPort: http-prom
      protocol: TCP
  selector:
    name: source-controller