# apps/base/part-db/postgres.yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &app partdb
spec:
  description: "PostgreSQL Part-DB DB"
  imageName: postgresql
  instances: 2
  bootstrap:
    initdb:
      database: *app
      owner: PARTDB_USER
      secret:
        name: *app-cnpg-user-secret
  storage:
    storageClass: longhorn
    size: 100Mi
  resources:
    requests:
      memory: 500Mi
      cpu: 300m
    limits:
      memory: 1Gi
      cpu: 800m
  # monitoring:
  #   enablePodMonitor: true