# apps/base/part-db/pvc-media.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: partdb-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
