# apps/base/part-db/pvc-uploads.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: partdb-uploads
spec:
  volumeName: partdb-uploads
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi # Dummy value
