# infrastructure/base/grafana-loki/kustomization.yaml
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - configmap.yaml
  - release.yaml
