# infrastructure/base/openhab/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
- namespace.yaml
- longhorn-prometheus-servicemonitor.yaml
- longhorn-prometheus-rules.yaml
