# infrastructure/base/prometheus-longhorn/kustomization.yaml
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
- longhorn-prom-servicemonitor.yaml
- longhorn-prom-rules.yaml
