---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
stringData:
  AUTHENTIK_BOOTSTRAP_PASSWORD: ${SECRET_AUTHENTIK_BOOTSTRAP_PASSWORD}
  AUTHENTIK_BOOTSTRAP_TOKEN: ${SECRET_AUTHENTIK_TOKEN}
  AUTHENTIK_BOOTSTRAP_EMAIL: ${SECRET_EMAIL_0}
