# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:1pxF8tj0LlNfsmgZNuqdnQzpk3EhnF9qRUbJ9mPkTzMZoajelrOSHA==,iv:J+KJqyPChfaVOr918UEg8HvYIToXvGJzh88rNjBLv4c=,tag:rJ8gOM3TxFkDTso8lE++uA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBML0ZrNG5xQzNUQXo5WXJX
            bDJLK1dqZEtxRFlmMFpRdnlMa0dQV3BxVWlzCjdiOFcrUk93L0M2OFhCd1lPeGd3
            QmlONXdnWXQ2QlZKRjQ3OVFjMDJnRkUKLS0tIG1qKzh5SEJZWitBanpJN2hnTUR2
            b0o4SGJWZm92ckM3MXZzSFM3NWQvVFEKBIVE8RwFstyKzUic1Wi+MCgziNcjEwWE
            AjjSrdrm271Bm5Y4wsNr19cAiJL5QzR8dWCZylkIoJus5aNa49S1AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T08:03:31Z"
    mac: ENC[AES256_GCM,data:J9hQ2JKXF3BWPL8pHiQrMO9iH6fiql21eLxfYQGerU6105Jz/JmKZUmj9pQjJHx+hwyKHZjdqgHzVoi+GCvU2LN8f2D80I7DuJWMS5f4pLFwEewCheleL+7/9Ihf3+5FEr1u7kB1HE53rcyIPiPXHrTViGX7Dbp7AeVOQDvZKYQ=,iv:yXexNmHiNKzorhBTQT2wuyuYCI0MRQAUphfEbNA8+Ok=,tag:1Er8zMlggUvN7ANGFV/7Dg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.9.2
