apiVersion: v1
kind: Service
metadata:
  name: cert-manager-metrics
  labels:
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager-metrics
    release: prometheus
spec:
  type: ClusterIP
  ports:
    - name: cert-manager-metrics
      port: 9100
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager