# infrastructure/base/grafana-alloy/chart.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: grafana
spec:
  interval: 10m0s
  chart: alloy
  sourceRef:
    kind: HelmRepository
    name: grafana
