# infrastructure/base/grafana-loki/ingressroute.yaml
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: loki
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`fix-me.example.com`)"
      kind: Rule
      services:
        - name: loki
          port: 3100
  tls: {}
