# infrastructure/base/grafana-alloy/release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  # namespace: logging
spec:
  releaseName: alloy
  chart:
    spec:
      chart: alloy
      interval: 22h
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1h
  install:
    remediation:
      retries: 2
