# infrastructure/base/grafana-alloy/release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
Kind: HelmRelease
metadata:
  name: alloy
  namespace: logging
spec:
  chart:
    spec:
      interval: 5h
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 0.8.1
  releaseName: alloy
  targetNamespace: logging
  interval: 1h
