# infrastructure/base/grafana-alloy/repository.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-alloy
  namespace: flux-system
spec:
  # url: https://grafana.github.io/helm-charts
  # type: default
  url: oci://ghcr.io/grafana/charts
  type: oci
