# infrastructure/base/grafana-alloy/repository.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
spec:
  url: https://grafana.github.io/helm-charts/grafana
  type: default
