apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  prune: true
  path: ./apps/production
  sourceRef:
    kind: GitRepository
    name: flux-system
