# clusters/production/kustomization.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterconfig
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 5m0s
  retryInterval: 1m0s
  path: ./clusters/production/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # postBuild:
  #   substituteFrom:
  #     - kind: ConfigMap
  #       name: cluster-config
  #     - kind: Secret
  #       name: cluster-secrets
