# clusters/production/kustomization.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  retryInterval: 1m0s
  path: ./infrastructure/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: clusterconfig
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
#---
#apiVersion: notification.toolkit.fluxcd.io/v1beta1
#kind: Alert
#metadata:
#  name: flux-system
#  namespace: flux-system
#spec:
#  providerRef: 
#    name: on-call-slack
#  eventSeverity: info
#  eventSources:
#    - kind: Kustomization
#      name: '*'
#  exclusionList:
#    - "^Dependencies.*"