#
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system # this must be included otherwise Flux will delete itself
patches:
  - patch: |
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: all
        spec: 
          decryption:
            provider: sops
            secretRef:
              name: sops-age
    target:
      kind: Kustomization
      labelSelector: app.kubernetes.io/sops=enabled