# clusters/production/openhab.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: openhab
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/crazyelectron-io/openhab.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openhab
  namespace: flux-system
spec:
  interval: 10m0s
  prune: true
  path: ./kustomize/production
  sourceRef:
    kind: GitRepository
    name: openhab
  timeout: 2m0s
  validation: client
