# infrastructure/production/config/cluster-secrets.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    # namespace: flux-system
type: Opaque
stringData:
    MAIN_DOMAIN: ENC[AES256_GCM,data:aPq395+UWrd0E9iqD8E=,iv:S0A3vwF8mMaaCOVgwLXXYNcXC0HCqFo15lDlQDeZoeQ=,tag:L7ROnn3fuCZxtnwOdH9pHA==,type:str]
    HARBOR_REGISTRY: ENC[AES256_GCM,data:Ud8+Khgnpf/j/wi1VqN7tVOXJhKQ6ZL43fJWwWYAJA==,iv:+A+yFJcACuc0zZzKHDAsb7mFsoItAOqzk2tseqLzx/g=,tag:dmlAWu3pQm7ePOsIC5twsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRVJySFdwbm1Wb3RvTDVC
            dTBOVUN4REtBY0dRV2gvUGFaMEE5WjU3eGtnClBQSUJxQ2tpZXBKVXYxK0gwMngw
            Zm00ZjZocW1GSHRjT1AzQURZQUNsVm8KLS0tIHlORTFBTkw1c1JMT2ZvYUNWdEcv
            TkZDYlA5SE85Vk1FQjFleGhDRnY2amcKrH0qGg3IODf7Ye/HNDdbcJOq7E3xah7K
            eWyAZws5PMjOCk8pQvEQ6igoc7olkvL0MYv0CApXNhYxVudrdqGisw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-01T15:21:31Z"
    mac: ENC[AES256_GCM,data:rakMa7UW9SN2Z555Gz0Nh3UpLeImzRhIY2H2Sdx9EIOzkvSQI+N6r39vfQ/DcaSv58N2K0dBqWoEI01dKsnOWvP4w09M0HoKP3D5pz+uhI43b30JEAGFss24PVAeUq431+LB2hdrqoCKZ6Qa9ep8OILnVg+mG1jBilvOThDQk+4=,iv:6oX+jIn6YVQJr+MDKjPtT26uXoeE1GKGWi22OQ562WE=,tag:cNEuKJmOS+jKKxu3tATFog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
