apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - deployment.yaml
  - issuer.yaml
  - mutating-webhook-configuration.yaml
  # TODO: Needs attention as CIDR is different per cluster
  # - network-policy.yaml
  - service.yaml
  - serviceaccount.yaml
