# infrastructure/production/grafana-alloy/chart-patch.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: grafana-alloy
  namespace: flux-system
spec:
  interval: 2h
  chart: grafana/alloy
  version: 0.8.1
  sourceRef:
    kind: HelmRepository
    name: grafana-alloy
