# infrastructure/production/grafana-alloy/chart-patch.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: grafana
spec:
  interval: 1h
  chart: alloy
  version: 0.8.0
  sourceRef:
    kind: HelmRepository
    name: grafana
