# infrastructure/production/grafana-alloy/kustomization.yaml
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
- ../../base/grafana-alloy
- namespace.yaml
patches:
  - path: ingressroute-patch.yaml
    target:
      kind: IngressRoute
  - path: release-patch.yaml
    target:
      kind: HelmRelease
