# k3s-flux-homekube:infrastructure/production/grafana-alloy/release-patch.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  releaseName: alloy
  chart:
    spec:
      version: 0.8.0
  interval: 10m0s
