apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &app grafana
  release: prometheus
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  endpoints:
  - port: http
    interval: 1m
    scrapeTimeout: 30s
    honorLabels: true
    path: /metrics
    scheme: http
    tlsConfig: {}
    relabelings: []
    metricRelabelings: []
  jobLabel: grafana
  selector:
    matchLabels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  namespaceSelector:
    matchNames:
      - monitoring-system