apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &app grafana
  labels:
    app.kubernetes.io/name: *app
    release: prometheus    
spec:
  endpoints:
  - targetPort: 9100
    interval: 30s
    scrapeTimeout: 60s
    honorLabels: true
    path: /metrics
  jobLabel: grafana
  selector:
    matchLabels:
      app.kubernetes.io/name: *app
      release: prometheus
  # namespaceSelector:
  #   matchNames:
  #     - monitoring-system
