# apps/base/cloudnative-pg/release.yaml
# notes: See https://github.com/cloudnative-pg/cloudnative-pg
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  releaseName: cloudnative-pg
  chart:
    spec:
      chart: cnpg/cloudnative-pg
      interval: 22h
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    image:
      repository: cloudnative-pg
      pullPolicy: IfNotPresent
    nameOverride: ""
    fullnameOverride: ""
    crds:
      create: true
    # -- Operator configuration.
    config:
      create: true
      name: cnpg-controller-manager-config
      secret: false
      # -- The content of the configmap/secret, for all available options see
      # https://cloudnative-pg.io/documentation/current/operator_conf/#available-options
      data:
        INHERITED_LABELS: environment, workload, app
      # WATCH_NAMESPACE: namespace-a,namespace-b
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
    monitoring:
      podMonitorEnabled: false
      # -- Metrics relabel configurations to apply to samples before ingestion.
      podMonitorMetricRelabelings: []
      # -- Relabel configurations to apply to samples before scraping.
      podMonitorRelabelings: []
      # -- Additional labels for the podMonitor
      podMonitorAdditionalLabels: {}
      grafanaDashboard:
        create: false
