# apps/base/cloudnative-pg/repository.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cloudnative-pg
spec:
  url: https://cloudnative-pg.github.io/charts
  type: default
