# infrastructure/production/config/cluster-secrets.sops.yaml
---
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    MAIN_DOMAIN: moerman.online
