---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: media
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/crazyelectron-io/k3s-flux-media
  ref:
    branch: main
  secretRef:
    name: k3s-flux-media-git
