---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: 31.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    installCRDs: false
    # See https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
    deployment:
      enabled: true
      kind: Deployment
      replicas: 3
    providers:
      kubernetesCRD:
        # -- Load Kubernetes IngressRoute provider
        enabled: true
        ingressClass: traefik-external
        allowEmptyServices: true
        allowExternalNameServices: true
        allowCrossNamespace: true
        namespaces: []
      kubernetesIngress:
      # -- Load Kubernetes Ingress provider
        enabled: true
        allowExternalNameServices: true
        allowEmptyServices: true
        publishedService:
          enabled: false
    logs:
      general:
        level: INFO
      access:
        enabled: false
    additionalArguments:
      - "--metrics.prometheus=true"
      - "--serversTransport.insecureSkipVerify=true"
    # - "--providers.kubernetesingress.allowemptyservices=true"
    # - "--providers.kubernetesingress.allowexternalnameservices=true"
    # - "--providers.kubernetescrd.allowemptyservices=true"
    # - "--providers.kubernetescrd.allowexternalnameservices=true"
    ports:
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 80
        protocol: TCP
        redirectTo:
          port: websecure
          priority: 10
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true
      web-ext:
        port: 8008
        expose:
          default: true
        exposedPort: 81
        protocol: TCP
        redirectTo:
          port: websecure-ext
          priority: 10
      websecure-ext:
        port: 8444
        expose:
          default: true
        exposedPort: 444
        protocol: TCP
        tls:
          enabled: true
      metrics:
        # https://github.com/prometheus/prometheus/wiki/Default-port-allocations
        port: 9100
        expose:
          default: false
        exposedPort: 9100
        protocol: TCP
    service:
      enabled: true
      type: LoadBalancer
      annotations: {}
      labels: {}
      spec:
        loadBalancerIP: ${TRAEFIK_EXTERNAL_ENDPOINT}
      loadBalancerSourceRanges: []
      externalIPs: []
    rbac:
      enabled: true