apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-monitor
  labels:
    app.kubernetes.io/name: traefik-monitor
spec:
  endpoints:
    - port: traefik-metrics
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - traefik
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik-metrics
      release: prometheus