apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: nginx
  namespace: nginx
spec:
  chart: nginx-ingress
  version: 1.2.0
  sourceRef:
    name: nginx
    kind: HelmRepository
  interval: 1h
