# infrastructure/production/prometheus-longhorn/kustomization.yaml
---
namespace: logging
resources:
- ../../base/prometheus-longhorn
- ../../base/reloader
- namespace.yaml
# patchesStrategicMerge:
#   - deployment.yaml
