apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-update
  labels:
    name: harbor-update
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: harbor-update
          image: debian:12.6-slim
          command: ["/bin/bash", "-c", "/mnt/scripts/harbor-update.sh"]
          # env:
          #   - name: HARBOR_TOKEN
          #     value: "${SECRET_HARBOR_ROBOT_SECRET}"
          #   - name: HARBOR_URL
          #     value: "registry.${SECRET_DOMAIN_0}"
          #   - name: HARBOR_NAMESPACE
          #     value: "library"
          volumeMounts:
            - name: script-volume
              mountPath: /mnt/scripts
      initContainers:
      - name: init-permissions
        image: debian:12.6-slim
        command: ["/bin/bash", "-c", "cp /scripts/harbor-update.sh /mnt/scripts/ && chmod +x /mnt/scripts/harbor-update.sh && cp /scripts/harbor-images.txt /mnt/scripts/"]
        volumeMounts:
        - name: harbor-update-script
          mountPath: /scripts/harbor-update.sh
          subPath: harbor-update.sh
        - name: harbor-update-list
          mountPath: /scripts/harbor-images.txt
          subPath: harbor-images.txt
        - name: script-volume
          mountPath: /mnt/scripts
      volumes:
      - name: harbor-update-script
        configMap:
          name: harbor-update-script-configmap
      - name: harbor-update-list
        configMap:
          name: harbor-update-list-configmap
      - name: script-volume
        emptyDir: {}
