---
apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-robot-account
  labels:
    name: harbor-robot-account
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: harbor-robot-account
          image: debian:12.6-slim
          command: ["/bin/bash", "-c", "ls -al /mnt/scripts", "/mnt/scripts/robot-account.sh"]
          volumeMounts:
          - name: script-volume
            mountPath: /mnt/scripts
      initContainers:
      - name: init-permissions
        image: debian:12.6-slim
        command: ["/bin/bash", "-c", "cp /scripts/robot-account.sh /mnt/scripts/robot-account.sh && chmod +x /mnt/scripts/robot-account.sh"]
        volumeMounts:
        - name: robot-account-script
          mountPath: /scripts
        - name: script-volume
          mountPath: /mnt/scripts
      volumes:
      - name: robot-account-script
        configMap:
          name: robot-script-configmap
      - name: script-volume
        emptyDir: {}