---
apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-robot-account
  labels:
    name: harbor-robot-account
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: harbor-robot-account
          image: debian:12.6-slim
          command: ["/bin/bash", "-c", "/mnt/scripts/robot-account.sh"]
          volumeMounts:
          - name: robot-account-script
            mountPath: /mnt/scripts
      initContainers:
      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "chmod +x /mnt/scripts/robot-account.sh"]
        volumeMounts:
        - name: robot-account-script
          mountPath: /mnt/scripts
      volumes:
      - name: robot-account-script
        configMap:
          name: robot-script-configmap