apiVersion: v1
kind: ConfigMap
metadata:
  name: robot-script-configmap
data:
  robot-account.sh: |
    #!/bin/bash

    echo ".......... Installing Required Packages ............"
    apt-get update
    apt-get install --no-install-recommends --no-install-suggests curl jq ca-certificates -y

    echo ".......... Creating Harbor Robot Account ............"

    # Create robot account
    ROBOT_RESPONSE=$(curl -v -u "${SECRET_HARBOR_ADMIN_USER}:dirmEf-zagvi0-tezdup" "https://registry.${SECRET_DOMAIN_0}/api/v2.0/robots" \
      -H "Content-Type: application/json" \
      -d '{
        "name": "automation",
        "description": "Robot account for Automation",
        "level": "project",
        "permissions": [
          {
            "kind": "project",
            "namespace": "library",
            "access": [
              {
                "action": "pull",
                "resource": "repository"
              },
              {
                "action": "push",
                "resource": "repository"
              },
              {
                "action": "create",
                "resource": "tag"
              },
              {
                "action": "delete",
                "resource": "tag"
              },
              {
                "action": "create",
                "resource": "artifact-label"
              },
              {
                "action": "list",
                "resource": "artifact"
              },
              {
                "action": "list",
                "resource": "repository"
              }
            ]
          }
        ]
      }')

    echo ".. $ROBOT_RESPONSE .."
    # Extract robot account name and secret
    ROBOT_ACCOUNT=$(echo $ROBOT_RESPONSE | jq -r '.name')
    ROBOT_ID=$(echo $ROBOT_RESPONSE | jq -r '.id')
    ROBOT_SECRET=$(echo $ROBOT_RESPONSE | jq -r '.secret')

    echo ".......... Harbor Robot Account Created ............"
    # Output robot account details for debugging purposes
    echo "Robot Account: $ROBOT_ACCOUNT"
    echo "Robot ID: $ROBOT_ID"
    echo "Robot Secret: $ROBOT_SECRET"

    # }' "https://registry.${SECRET_DOMAIN_0}/api/v2.0/robots" -w "%{http_code}" -o /dev/null -s | grep -E "201|409"

    # if [ $? -eq 0 ]; then
    #   echo ".......... Creating Kubernetes Secret for Robot Account ............"
    #   kubectl create secret generic harbor-robot-account --from-literal=robot-account.json="$(curl -s -u "${SECRET_HARBOR_ADMIN_USER}:$(cat /etc/harbor/admin-password)" "https://registry.${SECRET_DOMAIN_0}/api/v2.0/robots/automaton")"
    #   echo ".......... Kubernetes Secret Created ............"
    # else
    #   echo ".......... Failed to Create Harbor Robot Account or Secret ............"
    #   exit 1
    # fi


# ansible.builtin.uri:
#   url_username: "{{harbor_admin_user}}"
#   url_password: 'F#esG33ST'
#   url: "https://registry.moerman.online/api/v2.0/robots/{{create_robot.json.id}}"
#   validate_certs: yes
#   method: PATCH
#   headers:
#     Content-Type: application/json
#   body_format: json
#   force_basic_auth: true
#   status_code: [200]
#   body: |
#     {
#       "secret": "{{harbor_robot_key}}"
#     }