---
apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-robot-account
  labels:
    name: harbor-robot-account
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: harbor-robot-account
          image: debian:12.6-slim
          command: ["/bin/bash", "-c", "/scripts/robot-account.sh"]
          volumeMounts:
          - name: robot-account-script
            mountPath: /scripts
      volumes:
      - name: robot-account-script
        configMap:
          name: robot-script-configmap