# k3s-flux-homekube.git:apps/openhab/production/kustomization.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openhab
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: openhab
  path: "./kustomize/production"
  prune: true
  timeout: 1m
