# apps/production/cloudnative-pg/release-patch.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  values:
    replicaCount: 3
    image:
      repository: ${HARBOR_REGISTRY}/cloudnative-pg
      tag: 1.24.0
    nameOverride: cloudnative-pg
    # fullnameOverride: "" 
