apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ittools-external
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`tools.${SECRET_DOMAIN_0}`)"
      kind: Rule
      services:
        - name: http
          port: 8080
  tls: {}