# infrastructure/base/prometheus-operator/release.yaml 
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app prometheus-operator
spec:
  releaseName: *app
  chart:
    spec:
      chart: alloy
      interval: 22h
      sourceRef:
        kind: OCIRepository
        name: kube-prometheus
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      imageRegistry: ${HARBOR_REGISTRY}
      storageClass: longhorn
    fullnameOverride: prometheus
    operator:
      enabled: false
    prometheus:
      enabled: true
      image:
        repository: prometheus
        tag: 2.54.1
      ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
      resourcesPreset: "small"
      retention: 10d
      retentionSize: ""
      replicaCount: 1
      logLevel: info
      logFormat: logfmt
      persistence:
        enabled: true
        storageClass: longhorn
        size: 8Gi
    alertmanager:
      image:
        repository: alertmanager
        tag: 0.27.0-debian-12-r23
      resourcesPreset: "nano"
      ## Alertmanager configuration
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ['job']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: 'null'
          routes:
            - match:
                alertname: Watchdog
              receiver: 'null'
        receivers:
          - name: 'null'
      replicaCount: 1
      logLevel: info
      logFormat: logfmt
      retention: 120h
      persistence:
        enabled: true
        storageClass: longhorn
        size: 8Gi
    exporters:
      node-exporter:
        enabled: true
      kube-state-metrics:
        enabled: true
    kube-state-metrics:
      serviceMonitor:
        enabled: true
        honorLabels: true
    blackboxExporter:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/blackbox-exporter
        tag: 0.25.0-debian-12-r17
      configuration: |
        "modules":
          "http_2xx":
            "http":
              "preferred_ip_protocol": "ip4"
            "prober": "http"
          "http_post_2xx":
            "http":
              "method": "POST"
              "preferred_ip_protocol": "ip4"
            "prober": "http"
          "irc_banner":
            "prober": "tcp"
            "tcp":
              "preferred_ip_protocol": "ip4"
              "query_response":
              - "send": "NICK prober"
              - "send": "USER prober prober prober :prober"
              - "expect": "PING :([^ ]+)"
                "send": "PONG ${1}"
              - "expect": "^:[^ ]+ 001"
          "pop3s_banner":
            "prober": "tcp"
            "tcp":
              "preferred_ip_protocol": "ip4"
              "query_response":
              - "expect": "^+OK"
              "tls": true
              "tls_config":
                "insecure_skip_verify": false
          "ssh_banner":
            "prober": "tcp"
            "tcp":
              "preferred_ip_protocol": "ip4"
              "query_response":
              - "expect": "^SSH-2.0-"
          "tcp_connect":
            "prober": "tcp"
            "tcp":
              "preferred_ip_protocol": "ip4"
      existingConfigMap: ""
    kubeApiServer:
      enabled: true
    kubeControllerManager:
      enabled: true
      namespace: kube-system
    kubeScheduler:
      enabled: true
      namespace: kube-system
    coreDns:
      enabled: true
      namespace: kube-system
    kubeProxy:
      enabled: true
      namespace: kube-system
