apiVersion: v1
kind: Secret
metadata:
    name: grafana-cnpg-user-secret
    annotations:
        replicator.v1.mittwald.de/replicate-to: monitoring-system,cnpg-system,automation,flux-system
type: kubernetes.io/basic-auth
stringData:
    username: ${SECRET_GRAFANA_PG_USER}
    password: ${SECRET_GRAFANA_PG_PASSWORD}
