# apps/base/home-assistant/configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-conf
data:
  configuration.yaml: |
    # --- Loads default set of integrations. Do not remove.
    default_config:
    # --- Required to set the reverse proxy parameters
    http:
      ip_ban_enabled: false
      login_attempts_threshold: 100
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 172.18.0.0/24
        - 127.0.0.1
        - ::1
        - fe80::/64
        - fe00::/64
        - fd00::/64
    auth_header:
      username_header: X-ak-hass-user
      debug: true
    # --- Optionally, if something is not working right, add this block below to get more information
    logger:
        default: info
        logs:
            custom_components.auth_header: debug
    # --- Use Postgresql HA setup as recorder
    recorder:
      auto_purge: false
      purge_keep_days: 3660
      db_url: postgresql://${HOMEASSISTANT_PG_USER}:${HOMEASSISTANT_PG_PASSWORD}@${HOMEASSISTANT_PG_HOST}/homeassistant_pg_db
      db_retry_wait: 10
    # --- Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
    # --- 
    mqtt:
      sensor:
        - name: "Solarpower"
          state_topic: "/energy/inverter"
          unit_of_measurement: "W"
          value_template: {% raw %}"{{ value_json.power | round(0) }}{% endraw %}"
          json_attributes_topic: "/energy/inverter"
    # --- 
    media_player:
      - platform: yamaha
        host: 10.20.1.112
  automations.yaml: |
    # Automations go here
  scripts.yaml: |
    # Scripts go here
  scenes.yaml: |
    # Scenes go here
