# apps/base/home-assistant/postgres.yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homeassistant-cluster
spec:
  description: "PostgreSQL Home Assistant DB"
  imageName: postgresql
  instances: 2
  bootstrap:
    initdb:
      database: homeassistant_db
      owner: ${HOMEASSISTANT_USER}
      secret:
        name: homeassistant-cnpg-user-secret
  storage:
    storageClass: longhorn
    size: 100Mi
  resources:
    requests:
      memory: 500Mi
      cpu: 300m
    limits:
      memory: 1Gi
      cpu: 1
  monitoring:
    enablePodMonitor: true