---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
  annotations:
    replicator.v1.mittwald.de/replicate-to: default,media,monitoring-system,harbor-system,traefik
data:
  CONFIG_UDMPRO_IP_ADDRESS: 10.0.0.1
  CONFIG_NFS_SERVER_IP_ADDRESS: 10.100.0.2
  TRAEFIK_EXTERNAL_ENDPOINT: 10.100.0.21
  CONFIG_USENET_SERVER: news.eweka.nl
  CONFIG_MOSQUITTO_LB_ADDRESS: 10.100.0.31
  CONFIG_INFLUXDB_LB_ADDRESS: 10.100.0.33
  CONFIG_HOMEASSISTANT_LB_ADDRESS: 10.100.0.30