apiVersion: v1
kind: Secret
metadata:
    name: authentik-cnpg-user-secret
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:Z/FUtBjm9rAMFCY2dHS6B9SkSxYimAJKwApz,iv:OV8ZGZQ6PC18dWq+9207w/4+mH6DdoEmBrDgpKWEsnw=,tag:w8owP/BocRQbbRzAwVt2Xg==,type:str]
    password: ENC[AES256_GCM,data:G8pIHJy8TXYXysL7VeHkNCnxLlSUr2x2o93MXPfogw==,iv:ukd7tvrgqk1iZtpw1bvGaNqusGr3YtcopNQyKmPrCZs=,tag:miVkYZoPHyso7fRJdrEBzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZmxrak50b1ZwRXpJampO
            MWU3TEhWTXJDUWRLNkVzVmovWFN6YUJ6MUJ3Ck9SZ2taVy9iSGRSbC80RUdxMGo0
            clRNc3VZeCt0dzVtSkpMMklBRE8vT3MKLS0tIDBvSXdSeWNGbkM4dzQ1WGZFYjh0
            YUswNnVBRkU2dDFUd28yNlhXRVJ6bUEK4vFUgH0AerBClZASH1jBB/Itwzy7bgew
            ePLYK/R/ZRKkU5aKNzn1ogT/eMZa9NIJUjHQoFxw36SAtnqKj1bFWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T10:23:31Z"
    mac: ENC[AES256_GCM,data:CiWQhuYRD/zbIZgfMF7Dekt9W9ijDOA/5DHaoQx4b+LbuRQhDUb8vFjCzjHK5+kW+/SjSo2oHc128Io4TA5gd2mRnwQ1pv0L+Seg+eGlqExeD33L9obhWQ4UAXAXV+T8sYMIjF9a38xaeilAZL8obfEqcP9LJeWEnq3ZDRIuv90=,iv:tkCoK7odIutXtiJAgP1WFVIc/5yF7ci7XblBksaRQPQ=,tag:IcqSdFLXYLb+bAznrDMDtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.9.2
