apiVersion: v1
kind: Secret
metadata:
    name: authentik-cnpg-user-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:yrpKZoVetUvLpVr2ufleGm4Vz6i4PYrxdwzC,iv:hXKvzrQzWDmvOOVs7BT5BJnW07cPKdBwMmisu8MNouE=,tag:bPaupbqWIt1xx9yYgD4ckA==,type:str]
    password: ENC[AES256_GCM,data:F9IE46eDA6M7bmTVxAshl/5U7jUq3dTTmAIgXUkWPQ==,iv:xpG7ynaRJ5M+DtflxqemU4EHcIJkF/I82bDwUWsVkPc=,tag:QMUzqLheQKmT29lYgM+mcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZmxrak50b1ZwRXpJampO
            MWU3TEhWTXJDUWRLNkVzVmovWFN6YUJ6MUJ3Ck9SZ2taVy9iSGRSbC80RUdxMGo0
            clRNc3VZeCt0dzVtSkpMMklBRE8vT3MKLS0tIDBvSXdSeWNGbkM4dzQ1WGZFYjh0
            YUswNnVBRkU2dDFUd28yNlhXRVJ6bUEK4vFUgH0AerBClZASH1jBB/Itwzy7bgew
            ePLYK/R/ZRKkU5aKNzn1ogT/eMZa9NIJUjHQoFxw36SAtnqKj1bFWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T11:19:16Z"
    mac: ENC[AES256_GCM,data:S4zr9iIuuco0HUn6yoPwEKLCSMXL6S04A8L5mqyty0f+82BOssvnz6zGhgxB8W48I4TLyhGWiQUxTi7wDPkdjOFOVcurwsymNOVGJDPjAo9OPhperYsAooJGkxB9+b23D7F6ZDLVjsSx1mq2NnaK3Z7Ua2WP106cQY7mYKwVXP4=,iv:OmjmTjfUIM2UCYXYaqip3vvqmcYeZRudkLe5EEiz+Ho=,tag:9yYTY9NCl2Rs07HjiYr90A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.9.2
